### ISSUE TITLE
Flow's mentioned twice in the README.md

### ISSUE THREAD

**Issue by codeOfRobin** [malcommac/Flow#2]
Hey! I noticed, you've mentioned Flow twice in your README under "Other projects". I'd make a PR to fix it, but I'm not sure which description you'd prefer ¯\\\_(ツ)\_/¯  (both're excellent!)

![screen shot 2017-10-18 at 10 25 14 pm](https://user-images.githubusercontent.com/5009041/31731654-5c1209b0-b453-11e7-99cf-a23593758dd6.png)

**Comment by malcommac** [comment]
Fixed in PR.
Thanks 👍
