### ISSUE TITLE
Some rows are hidden if not scroll

### ISSUE THREAD

**Issue by bellots** [malcommac/Flow#4]
I've got many different rows which are created in some utility (and dedicated) functions. In every function I return an array **[RowProtocol]**. The behavior is that when I reload, some of before rows are hidden, until I scroll the tableView. Contents are loaded after fetching data from server.

**Comment by bellots** [comment]
I checked that the problem seems to be the contentSize that at the beginning is not correct.

**Comment by malcommac** [comment]
Solv
